### ISSUE TITLE
FirebaseError: There was an unknown problem while trying to parse function triggers.

### ISSUE THREAD

**Issue by valorloff** [Bolket/next-firebase-functions#10]
Hi!
with big hope finded this example, but also bad luck (:
`FirebaseError: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.`
node -v
v6.12.0
I updated all packages - firebase-tools, admin, functions...

jthegedus/firebase-functions-next-example also not working (:

i'm dreaming get working example of next.js firebase-function.
Anybody help me!

**Comment by sarovin** [comment]
when have you this error? With `yarn serve`?

**Comment by valorloff** [comment]
sorry,
Yes!
With` yarn serve`

**Comment by sarovin** [comment]
I think that it is a problem in firebase-functions. See here => https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/86
